image: python:3.7
before_script:
  - chmod +x ./configure
  - ./configure
  - make
  - make install
test:
  script:
    - . $HOME/bin/net.splitcells.os.state.interface.commands.managed/command.managed.export.bin
    - ./bin/test