# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install this framework and run tests.
      run: |
        # TODO apt install -y python3 # Check if Python3 is present.
        cd $GITHUB_WORKSPACE
        # TODO TOFIX Make is not present on image ubuntu-latest which is provided by act.
        # chmod +x ./configure
        # ./configure
        # make
        # make install
        chmod +x ./bin/install
        ./bin/install
        . $HOME/bin/net.splitcells.os.state.interface.commands.managed/command.managed.export.bin
        ./bin/test
