name: Continous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        java-version: [11]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE
          ./bin/build